package catalog

import (
	"fmt"
	"os"
	"sort"

	"github.com/lancekrogers/work-index/internal/config"
	"github.com/lancekrogers/work-index/internal/github"
	"gopkg.in/yaml.v3"
)

// Project is a merged view: GitHub data + curation editorial metadata.
type Project struct {
	Name         string `yaml:"name"`
	Org          string `yaml:"org"`
	URL          string `yaml:"url"`
	Description  string `yaml:"description"`
	Language     string `yaml:"language"`
	Stars        int    `yaml:"stars"`
	Created      string `yaml:"created"`
	Pushed       string `yaml:"pushed"`
	Fork         bool   `yaml:"fork"`
	OwnerCommits *int   `yaml:"owner_commits,omitempty"`

	// Editorial (from curation.yaml catalog).
	Category     string `yaml:"category"`
	Summary      string `yaml:"summary,omitempty"`
	WhyItMatters string `yaml:"why_it_matters,omitempty"`
	Status       string `yaml:"status,omitempty"`
}

// ID returns org/name.
func (p *Project) ID() string {
	return p.Org + "/" + p.Name
}

// DisplaySummary returns the summary if set, otherwise the GitHub description.
func (p *Project) DisplaySummary() string {
	if p.Summary != "" {
		return p.Summary
	}
	return p.Description
}

// Category holds the rendered list of projects for a category page.
type Category struct {
	Slug     string
	Title    string
	Desc     string
	Projects []Project
}

// RawFile is the on-disk format of repos-raw.yaml.
type RawFile struct {
	Repos []github.Repo `yaml:"repos"`
}

// MergeProjects takes raw repos and curation data, returns catalog-included projects.
func MergeProjects(repos []github.Repo, cur *config.Curation) []Project {
	var projects []Project

	for _, r := range repos {
		id := r.ID()
		entry := cur.CatalogEntryFor(id)
		if entry == nil {
			continue
		}

		p := Project{
			Name:         r.Name,
			Org:          r.Org,
			URL:          r.URL,
			Description:  r.Description,
			Language:     r.Language,
			Stars:        r.Stars,
			Created:      r.Created,
			Pushed:       r.Pushed,
			Fork:         r.IsFork,
			OwnerCommits: r.OwnerCommits,
			Category:     entry.Category,
			Status:       entry.Status,
		}

		if entry.Summary != "" {
			p.Summary = entry.Summary
		}
		if entry.WhyItMatters != "" {
			p.WhyItMatters = entry.WhyItMatters
		}

		projects = append(projects, p)
	}

	// Sort by created date descending (newest first).
	sort.Slice(projects, func(i, j int) bool {
		return projects[i].Created > projects[j].Created
	})

	return projects
}

// GroupByCategory groups projects into categories.
func GroupByCategory(projects []Project, categories map[string]CategoryMeta) []Category {
	groups := make(map[string][]Project)
	for _, p := range projects {
		groups[p.Category] = append(groups[p.Category], p)
	}

	var result []Category
	for slug, meta := range categories {
		cat := Category{
			Slug:     slug,
			Title:    meta.Title,
			Desc:     meta.Desc,
			Projects: groups[slug],
		}
		result = append(result, cat)
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].Title < result[j].Title
	})

	return result
}

// CategoryMeta holds display metadata for a category.
type CategoryMeta struct {
	Title string
	Desc  string
}

// WriteRawFile writes repos-raw.yaml.
func WriteRawFile(path string, repos []github.Repo, cur *config.Curation, timestamp string) error {
	type rawEntry struct {
		Name         string `yaml:"name"`
		Org          string `yaml:"org"`
		URL          string `yaml:"url"`
		Description  string `yaml:"description"`
		Language     string `yaml:"language"`
		Stars        int    `yaml:"stars"`
		Created      string `yaml:"created"`
		Pushed       string `yaml:"pushed"`
		Fork         bool   `yaml:"fork"`
		OwnerCommits *int   `yaml:"owner_commits,omitempty"`
		Status       string `yaml:"status"`
	}

	entries := make([]rawEntry, 0, len(repos))
	for _, r := range repos {
		entries = append(entries, rawEntry{
			Name:         r.Name,
			Org:          r.Org,
			URL:          r.URL,
			Description:  r.Description,
			Language:     r.Language,
			Stars:        r.Stars,
			Created:      r.Created,
			Pushed:       r.Pushed,
			Fork:         r.IsFork,
			OwnerCommits: r.OwnerCommits,
			Status:       cur.ComputeStatus(r.ID()),
		})
	}

	type rawFile struct {
		Repos []rawEntry `yaml:"repos"`
	}

	header := fmt.Sprintf("# Auto-generated by `workindex sync`. DO NOT edit by hand.\n# Last synced: %s\n\n", timestamp)

	data, err := yaml.Marshal(rawFile{Repos: entries})
	if err != nil {
		return fmt.Errorf("marshal repos-raw: %w", err)
	}

	return os.WriteFile(path, append([]byte(header), data...), 0644)
}
