#!/usr/bin/env bash
# sync-repos.sh
#
# Syncs all public, non-fork repos from the authenticated user's account and
# every accessible GitHub org into repos-raw.yaml. This is the raw inventory —
# curate from it into projects.yaml to choose what appears in your catalog.
#
# Requires: gh (authenticated), jq, yq

set -euo pipefail

OUTPUT="repos-raw.yaml"
CATALOG="projects.yaml"

# --- Collect owners -----------------------------------------------------------

USER=$(gh api user --jq '.login')
ORGS=$(gh api user/orgs --jq '.[].login')
ALL_OWNERS=$(printf '%s\n%s\n' "$USER" "$ORGS" | sort -u)

echo "Syncing public repos from:"
printf '%s\n' "$ALL_OWNERS" | sed 's/^/  - /'
echo ""

# --- Build lookup of repos already curated into projects.yaml -----------------

CATALOG_REPOS=""
if [ -f "$CATALOG" ]; then
    CATALOG_REPOS=$(yq '.projects[]?.repo // ""' "$CATALOG" 2>/dev/null | grep -v '^$' || true)
fi

in_catalog() {
    local url="$1"
    if [ -z "$CATALOG_REPOS" ]; then
        echo "false"
        return
    fi
    if printf '%s\n' "$CATALOG_REPOS" | grep -qxF "$url"; then
        echo "true"
    else
        echo "false"
    fi
}

# --- Emit header --------------------------------------------------------------

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
cat > "$OUTPUT" <<HEADER
# Auto-generated by \`just sync-repos\`. DO NOT edit by hand.
#
# This is the raw inventory of all public, non-fork repos across your
# accessible GitHub orgs. Curate from this file into projects.yaml to choose
# what appears in your catalog.
#
# Last synced: ${TIMESTAMP}

repos:
HEADER

# --- Fetch and emit -----------------------------------------------------------

total=0
for owner in $ALL_OWNERS; do
    echo "Fetching public repos from ${owner}..."
    repos_json=$(gh repo list "$owner" \
        --limit 1000 \
        --visibility public \
        --no-archived \
        --source \
        --json name,description,url,primaryLanguage,pushedAt,createdAt,stargazerCount,isArchived,isFork 2>/dev/null || echo "[]")

    count=$(echo "$repos_json" | jq 'length')
    if [ "$count" = "0" ]; then
        echo "  (none)"
        continue
    fi

    # Emit each repo. Sorted by pushedAt descending so recent activity is on top per-owner.
    echo "$repos_json" | jq -c 'sort_by(.pushedAt) | reverse | .[]' | while IFS= read -r repo; do
        name=$(echo "$repo" | jq -r '.name')
        url=$(echo "$repo" | jq -r '.url')
        desc=$(echo "$repo" | jq -r '.description // ""')
        lang=$(echo "$repo" | jq -r '.primaryLanguage.name // "unknown"')
        stars=$(echo "$repo" | jq -r '.stargazerCount')
        created=$(echo "$repo" | jq -r '.createdAt' | cut -d'T' -f1)
        pushed=$(echo "$repo" | jq -r '.pushedAt' | cut -d'T' -f1)

        curated=$(in_catalog "$url")

        # Escape backslashes and double-quotes for YAML double-quoted string
        desc_escaped=$(printf '%s' "$desc" | sed 's/\\/\\\\/g; s/"/\\"/g')

        cat >> "$OUTPUT" <<REPO
  - name: ${name}
    org: ${owner}
    url: ${url}
    description: "${desc_escaped}"
    language: ${lang}
    stars: ${stars}
    created: ${created}
    pushed: ${pushed}
    in_catalog: ${curated}
REPO
    done

    total=$((total + count))
    echo "  ${count} repos"
done

echo ""
echo "Synced ${total} public repos to ${OUTPUT}"
