#!/usr/bin/env bash
# sync-repos.sh
#
# Syncs all public, non-fork repos from the authenticated user's account and
# every accessible GitHub org into repos-raw.yaml. This is the raw inventory —
# curate from it into projects.yaml to choose what appears in your catalog.
#
# Requires: gh (authenticated), jq, yq

set -euo pipefail

OUTPUT="repos-raw.yaml"
CATALOG="projects.yaml"

# --- Collect owners -----------------------------------------------------------

CONFIG="sync-config.yaml"
if [ ! -f "$CONFIG" ]; then
    echo "ERROR: ${CONFIG} not found. Cannot determine which owners to sync." >&2
    exit 1
fi

ALL_OWNERS=$(yq -r '.owners[]' "$CONFIG")
if [ -z "$ALL_OWNERS" ]; then
    echo "ERROR: ${CONFIG} has no owners listed under 'owners:'." >&2
    exit 1
fi

echo "Syncing public repos from owners in ${CONFIG}:"
printf '%s\n' "$ALL_OWNERS" | sed 's/^/  - /'
echo ""

# --- Build lookup sets for status computation ---------------------------------

CURATION="curation.yaml"

# URLs of repos already curated into projects.yaml (match on full URL)
CATALOG_URLS=""
if [ -f "$CATALOG" ]; then
    CATALOG_URLS=$(yq -r '.projects[]?.repo // ""' "$CATALOG" 2>/dev/null | grep -v '^$' || true)
fi

# org/name identifiers from curation.yaml
EXCLUDED_IDS=""
TODO_IDS=""
if [ -f "$CURATION" ]; then
    EXCLUDED_IDS=$(yq -r '.excluded[]? // ""' "$CURATION" 2>/dev/null | grep -v '^$' || true)
    TODO_IDS=$(yq -r '.todo[]? // ""' "$CURATION" 2>/dev/null | grep -v '^$' || true)
fi

# Compute status for a repo.
# Priority: included > excluded > todo > unreviewed
compute_status() {
    local url="$1"
    local id="$2"
    if [ -n "$CATALOG_URLS" ] && printf '%s\n' "$CATALOG_URLS" | grep -qxF "$url"; then
        echo "included"
        return
    fi
    if [ -n "$EXCLUDED_IDS" ] && printf '%s\n' "$EXCLUDED_IDS" | grep -qxF "$id"; then
        echo "excluded"
        return
    fi
    if [ -n "$TODO_IDS" ] && printf '%s\n' "$TODO_IDS" | grep -qxF "$id"; then
        echo "todo"
        return
    fi
    echo "unreviewed"
}

# --- Emit header --------------------------------------------------------------

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
cat > "$OUTPUT" <<HEADER
# Auto-generated by \`just sync-repos\`. DO NOT edit by hand.
#
# This is the raw inventory of all public, non-fork repos across your
# accessible GitHub orgs. Curate from this file into projects.yaml to choose
# what appears in your catalog.
#
# Last synced: ${TIMESTAMP}

repos:
HEADER

# --- Fetch and emit -----------------------------------------------------------

total=0
for owner in $ALL_OWNERS; do
    echo "Fetching public repos from ${owner}..."
    repos_json=$(gh repo list "$owner" \
        --limit 1000 \
        --visibility public \
        --no-archived \
        --source \
        --json name,description,url,primaryLanguage,pushedAt,createdAt,stargazerCount,isArchived,isFork 2>/dev/null || echo "[]")

    count=$(echo "$repos_json" | jq 'length')
    if [ "$count" = "0" ]; then
        echo "  (none)"
        continue
    fi

    # Emit each repo. Sorted by pushedAt descending so recent activity is on top per-owner.
    echo "$repos_json" | jq -c 'sort_by(.pushedAt) | reverse | .[]' | while IFS= read -r repo; do
        name=$(echo "$repo" | jq -r '.name')
        url=$(echo "$repo" | jq -r '.url')
        desc=$(echo "$repo" | jq -r '.description // ""')
        lang=$(echo "$repo" | jq -r '.primaryLanguage.name // "unknown"')
        stars=$(echo "$repo" | jq -r '.stargazerCount')
        created=$(echo "$repo" | jq -r '.createdAt' | cut -d'T' -f1)
        pushed=$(echo "$repo" | jq -r '.pushedAt' | cut -d'T' -f1)

        id="${owner}/${name}"
        status=$(compute_status "$url" "$id")

        # Escape backslashes and double-quotes for YAML double-quoted string
        desc_escaped=$(printf '%s' "$desc" | sed 's/\\/\\\\/g; s/"/\\"/g')

        cat >> "$OUTPUT" <<REPO
  - name: ${name}
    org: ${owner}
    url: ${url}
    description: "${desc_escaped}"
    language: ${lang}
    stars: ${stars}
    created: ${created}
    pushed: ${pushed}
    status: ${status}
REPO
    done

    total=$((total + count))
    echo "  ${count} repos"
done

echo ""
echo "Synced ${total} public repos to ${OUTPUT}"
